name: site-package/carousel
typeName: site_package_carousel
group: site_package
prefixFields: true
fields:
  - identifier: carousel_items
    type: Collection
    minitems: 1
    appearance:
      collapseAll: true
      levelLinksPosition: both
    fields:
      - identifier: image
        type: File
        allowed: common-image-types
        minitems: 1
        relationship: manyToOne
      - identifier: header
        type: Text
      - identifier: description
        type: Textarea
        enableRichtext: true
